/* Generated by AN DISI Unibo */ 
package it.unibo.ctxsistemas
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	println("MainCtxsistemas starting ...")
	QakContext.createContexts(
	        "localhost", this, "sistemasqak.pl", "sysRules.pl", "ctxsistemas"
	)
	println("MainCtxsistemas contexts created. Waiting ...")
	kotlinx.coroutines.delay(5000)
}

